version: '3.7'
services:
  obp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: obpmodif
    container_name: obp_nova
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    command: "bash run_servers"
    tty: true
