version: '3.7'
services:
  obp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: obp_nova
    container_name: obp_nova
    volumes:
      - /home/raul/.m2:/root/.m2
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    depends_on:
        - postgres
    command: "bash run_servers"
    tty: true
  postgres:
      image: postgres:latest
      container_name: postgres_obp
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=123456
