#!/bin/bash
echo "Ejecutando Servidores OBP_NOVASOLUTIONSYSTEMS"
cd /opt/OBP/API-Explorer
mvn package -DskipTests
nohup mvn jetty:run -Djetty.port=8082 &
cd /opt/OBP/Social-Finance
mvn package -DskipTests
nohup mvn jetty:run -Djetty.port=8081 &
cd /opt/OBP/OBP-API
nohup ./mvn.sh install -pl .,obp-commons && ./mvn.sh jetty:run -pl obp-api &
/bin/bash
